#!/bin/bash

if [ -f '/sys/class/power_supply/BAT0' ]; then
	bat='/sys/class/power_supply/BAT0'
else
	bat='/sys/class/power_supply/BAT1'
fi

per="$(cat "$bat/capacity")"
ac_stat="$(cat /sys/class/power_supply/*AC*/online || printf 0)"

icon () {

if [ "$per" -eq "100" ]; then
	[ "$ac_stat" = 1 ] && icon='󰂄' || icon='󰁹'
elif [ "$per" -gt "90" ]; then
	[ "$ac_stat" = 1 ] && icon='󰂋' || icon='󰂂'
elif [ "$per" -gt "80" ]; then
	[ "$ac_stat" = 1 ] && icon='󰂊' || icon='󰂁'
elif [ "$per" -gt "70" ]; then
	[ "$ac_stat" = 1 ] && icon='󰢞' || icon='󰂀'
elif [ "$per" -gt "60" ]; then
	[ "$ac_stat" = 1 ] && icon='󰂉' || icon='󰁿'
elif [ "$per" -gt "50" ]; then
	[ "$ac_stat" = 1 ] && icon='󰢝' || icon='󰁾'
elif [ "$per" -gt "40" ]; then
	[ "$ac_stat" = 1 ] && icon='󰂈' || icon='󰁽'
elif [ "$per" -gt "30" ]; then
	[ "$ac_stat" = 1 ] && icon='󰂇' || icon='󰁼'
elif [ "$per" -gt "20" ]; then
	[ "$ac_stat" = 1 ] && icon='󰂆' || icon='󰁻'
elif [ "$per" -gt "10" ]; then
	[ "$ac_stat" = 1 ] && icon='󰢜' || icon='󰁺'
else
	[ "$ac_stat" = 1 ] && icon='󰢟' || icon='󱃍'
fi
echo "$icon"
}

percent () {
	echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
exit
