#!/usr/bin/env bash

cache_file=$HOME/.cache/eww/services/wlsunset_state

initial_hook () {
  if [ ! -d $(dirname $cache_file) ]; then
    mkdir $(dirname $cache_file)
  fi
  if [ ! -f $cache_file ]; then
    echo off > $cache_file
  fi
}

get_state () {
  # check if wlsunset is running
  cat $cache_file
}

restore () {
  local state=$(get_state)
  if [[ $state == "on" ]]; then
    enable_wlsunset
  else
    disable_wlsunset
  fi
}

disable_wlsunset () {
  redshift -x 2>&1 > /dev/null
  # saving state
  echo off > $cache_file
}

enable_wlsunset () {
  redshift -x 2>&1 > /dev/null
  redshift -O 5700 2>&1 > /dev/null
  # saving new state
  echo on > $cache_file
}

toggle () {
  local state=$(get_state)
  if [[ $state == "on" ]]; then
    disable_wlsunset
  else
    enable_wlsunset
  fi
}

initial_hook

if [[ $1 == "state" ]]; then
  get_state
fi

if [[ $1 == "enable" ]]; then
  enable_wlsunset
fi

if [[ $1 == "disable" ]]; then
  disable_wlsunset
fi

if [[ $1 == "toggle" ]]; then
  toggle
fi

if [[ $1 == "restore" ]]; then
  restore
fi
