" global/environment variables:
	" get the folder that the config goes to (different on each OS)
	let mapleader = ' ' " sets the leader key
	let $MYVIMRCFOLDER = fnamemodify($MYVIMRC, ":p:h") .. "/.vim"

	" Preferences
	let g:Use_devicons = 1

" The plugins call file (vim-plug plugin manager)
	source $MYVIMRCFOLDER/plugins.vim
