-- cplex colorscheme header
vim.g.colors_name = "cplex"
-- Hints for panels
vim.api.nvim_set_hl(0, 'PanelHint', { fg = '#4c4c5f', bg = 'none', ctermfg = 239, ctermbg = 'none'})
-- General colors
vim.api.nvim_set_hl(0, 'Accent', { fg = '#2166a6', bg = 'none', ctermfg = 25, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Normal', { fg = '#d5d5e0', bg = '#18181a', ctermfg = 253, ctermbg = 234})
vim.api.nvim_set_hl(0, 'Float', { fg = '#d5d5e0', bg = '#18181a', ctermfg = 253, ctermbg = 234})
vim.api.nvim_set_hl(0, 'Include', { fg = '#d75f87', bg = 'none', ctermfg = 168, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Comment', { fg = '#5f875f', bg = 'none', ctermfg = 65, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Constant', { fg = '#e7e89f', bg = 'none', ctermfg = 187, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Delimiter', { fg = '#d5d5e0', bg = '#18181a', ctermfg = 253, ctermbg = 234})
vim.api.nvim_set_hl(0, 'String', { fg = '#c38872', bg = 'none', ctermfg = 173, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Character', { fg = '#c38872', bg = 'none', ctermfg = 173, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Boolean', { fg = '#af87d7', bg = 'none', ctermfg = 140, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Number', { fg = '#afd7af', bg = 'none', ctermfg = 151, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Float', { fg = '#afd7af', bg = 'none', ctermfg = 151, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Repeat', { fg = '#c586c0', bg = 'none', ctermfg = 175, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Conditional', { fg = '#af87d7', bg = 'none', ctermfg = 140, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#87afff', bg = 'none', ctermfg = 111, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Operator', { fg = '#af5f87', bg = 'none', ctermfg = 132, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Function', { fg = '#e8e6b5', bg = 'none', ctermfg = 187, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#e4e4e4', bg = 'none', ctermfg = 254, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Field', { fg = '#c4e4ff', bg = 'none', ctermfg = 189, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Type', { fg = '#5fafaf', bg = 'none', ctermfg = 73, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Directory', { fg = '#5fafff', bg = 'none', ctermfg = 75, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Error', { fg = '#f44747', bg = 'none', ctermfg = 203, ctermbg = 'none', bold = true})
vim.api.nvim_set_hl(0, 'Special', { fg = '#5fafff', bg = 'none', ctermfg = 75, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Folded', { fg = '#5fafff', bg = '#585858', ctermfg = 75, ctermbg = 240})
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#d5d5e0', bg = '#2166a6', ctermfg = 253, ctermbg = 25})
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#b2b2b2', bg = '#2b2b3b', ctermfg = 249, ctermbg = 236})
vim.api.nvim_set_hl(0, 'StatusLineSep', { fg = '#2166a6', bg = '#2b2b3b', ctermfg = 25, ctermbg = 236})
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#b2b2b2', bg = '#2b2b3b', ctermfg = 249, ctermbg = 236})
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#d2d2d2', bg = '#4b4b4b', ctermfg = 252, ctermbg = 239})
vim.api.nvim_set_hl(0, 'PmenuSbar', { fg = 'none', bg = '#34343a', ctermfg = 'none', ctermbg = 237})
vim.api.nvim_set_hl(0, 'PmenuThumb', { fg = 'none', bg = '#4b4b4b', ctermfg = 'none', ctermbg = 239})
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#d5d5e0', bg = '#18181a', ctermfg = 253, ctermbg = 234})
vim.api.nvim_set_hl(0, 'TabLineSelSep', { fg = '#18181a', bg = '#0c0c0c', ctermfg = 234, ctermbg = 232})
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#b2b2b2', bg = '#101013', ctermfg = 249, ctermbg = 233})
vim.api.nvim_set_hl(0, 'TabLineFill', { fg = 'none', bg = '#0c0c0c', ctermfg = 'none', ctermbg = 232})
vim.api.nvim_set_hl(0, 'TabLineSep', { fg = '#101013', bg = '#0c0c0c', ctermfg = 233, ctermbg = 232})
vim.api.nvim_set_hl(0, 'WildMenu', { fg = '#b2b2b2', bg = '#2b2b3b', ctermfg = 249, ctermbg = 236})
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#b2b2b2', bg = 'none', ctermfg = 249, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'ModeMsg', { fg = '#b2b2b2', bg = 'none', ctermfg = 249, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'SignColumn', { fg = 'none', bg = '#18181a', ctermfg = 'none', ctermbg = 234})
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#d5d5e0', bg = 'none', ctermfg = 253, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'CursorLine', { fg = 'none', bg = '#202028', ctermfg = 'none', ctermbg = 235})
vim.api.nvim_set_hl(0, 'CursorColumn', { fg = 'none', bg = '#202028', ctermfg = 'none', ctermbg = 235})
vim.api.nvim_set_hl(0, 'ColorColumn', { fg = 'none', bg = '#202028', ctermfg = 'none', ctermbg = 235})
vim.api.nvim_set_hl(0, 'Cursor', { fg = 'none', bg = 'none', ctermfg = 'none', ctermbg = 'none', reverse = true})
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#34343a', bg = 'none', ctermfg = 237, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'WinSeparator', { fg = '#34343a', bg = 'none', ctermfg = 237, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'Search', { fg = 'none', bg = '#263e76', ctermfg = 'none', ctermbg = 24})
vim.api.nvim_set_hl(0, 'IncSearch', { fg = 'none', bg = '#724325', ctermfg = 'none', ctermbg = 58})
vim.api.nvim_set_hl(0, 'Visual', { fg = 'none', bg = '#263e76', ctermfg = 'none', ctermbg = 24})
vim.api.nvim_set_hl(0, 'VisualNOS', { fg = '#b2b2b2', bg = 'none', ctermfg = 249, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'NonText', { fg = '#585858', bg = 'none', ctermfg = 240, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#b2b2b2', bg = 'none', ctermfg = 249, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#83c99a', bg = 'none', ctermfg = 114, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#d7bf8e', bg = 'none', ctermfg = 180, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#942126', bg = 'none', ctermfg = 88, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'DiagnosticSignError', { fg = '#a70000', bg = 'none', ctermfg = 124, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'DiagnosticSignWarning', { fg = '#b7af5f', bg = 'none', ctermfg = 143, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'DiagnosticSignInformation', { fg = '#658beb', bg = 'none', ctermfg = 69, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', { fg = '#658beb', bg = 'none', ctermfg = 69, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'DiagnosticSignHint', { fg = '#e4e4e4', bg = 'none', ctermfg = 254, ctermbg = 'none'})
-- Specific colors (mainly for devicons)
vim.api.nvim_set_hl(0, 'c_F14C28', { fg = '#F14C28', bg = 'none', ctermfg = 202, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_019833', { fg = '#019833', bg = 'none', ctermfg = 29, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_DEA584', { fg = '#DEA584', bg = 'none', ctermfg = 180, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_E44D26', { fg = '#E44D26', bg = 'none', ctermfg = 166, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_F69A1B', { fg = '#F69A1B', bg = 'none', ctermfg = 208, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_9772FB', { fg = '#9772FB', bg = 'none', ctermfg = 99, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_E8274B', { fg = '#E8274B', bg = 'none', ctermfg = 161, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_F1E05A', { fg = '#F1E05A', bg = 'none', ctermfg = 221, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_1563FF', { fg = '#1563FF', bg = 'none', ctermfg = 27, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_185ABD', { fg = '#185ABD', bg = 'none', ctermfg = 25, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_41535B', { fg = '#41535B', bg = 'none', ctermfg = 239, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_B83998', { fg = '#B83998', bg = 'none', ctermfg = 132, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_E34C26', { fg = '#E34C26', bg = 'none', ctermfg = 166, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_358A5B', { fg = '#358A5B', bg = 'none', ctermfg = 65, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_427819', { fg = '#427819', bg = 'none', ctermfg = 64, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_563D7C', { fg = '#563D7C', bg = 'none', ctermfg = 60, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_599EFF', { fg = '#599EFF', bg = 'none', ctermfg = 75, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_CC3E44', { fg = '#CC3E44', bg = 'none', ctermfg = 167, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_F88A02', { fg = '#F88A02', bg = 'none', ctermfg = 208, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_FFA61A', { fg = '#FFA61A', bg = 'none', ctermfg = 214, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_E4B854', { fg = '#E4B854', bg = 'none', ctermfg = 179, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_D0BF41', { fg = '#D0BF41', bg = 'none', ctermfg = 179, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_6D8086', { fg = '#6D8086', bg = 'none', ctermfg = 66, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_A074C4', { fg = '#A074C4', bg = 'none', ctermfg = 140, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_E37933', { fg = '#E37933', bg = 'none', ctermfg = 173, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_8DC149', { fg = '#8DC149', bg = 'none', ctermfg = 107, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_ECECEC', { fg = '#ECECEC', bg = 'none', ctermfg = 255, ctermbg = 'none'})
vim.api.nvim_set_hl(0, 'c_51A0CF', { fg = '#51A0CF', bg = 'none', ctermfg = 74, ctermbg = 'none'})
-- Normal links
vim.api.nvim_set_hl(0, 'Title', { link = 'Normal'})
vim.api.nvim_set_hl(0, 'Todo', { link = 'Special'})
vim.api.nvim_set_hl(0, 'Statement', { link = 'Repeat'})
vim.api.nvim_set_hl(0, 'SpecialComment', { link = 'Special'})
vim.api.nvim_set_hl(0, 'CursorColumn', { link = 'CursorLine'})
vim.api.nvim_set_hl(0, 'String', { link = 'Character'})
-- Lsp links
vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultError', { link = 'DiagnosticSignError'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultWarning', { link = 'DiagnosticSignWarning'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultInformation', { link = 'DiagnosticSignInformation'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultInfo', { link = 'DiagnosticSignInfo'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultHint', { link = 'DiagnosticSignHint'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsVirtualTextError', { link = 'DiagnosticSignError'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsVirtualTextWarning', { link = 'DiagnosticSignWarning'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsVirtualTextInformation', { link = 'DiagnosticSignInformation'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsVirtualTextInfo', { link = 'DiagnosticSignInfo'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsVirtualTextHint', { link = 'DiagnosticSignHint'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsFloatingError', { link = 'DiagnosticSignError'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsFloatingWarning', { link = 'DiagnosticSignWarning'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsFloatingInformation', { link = 'DiagnosticSignInformation'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsFloatingInfo', { link = 'DiagnosticSignInfo'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsFloatingHint', { link = 'DiagnosticSignHint'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsSignError', { link = 'DiagnosticSignError'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsSignWarning', { link = 'DiagnosticSignWarning'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsSignInformation', { link = 'DiagnosticSignInformation'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsSignInfo', { link = 'DiagnosticSignInfo'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsSignHint', { link = 'DiagnosticSignHint'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsError', { link = 'DiagnosticSignError'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsWarning', { link = 'DiagnosticSignWarning'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsInformation', { link = 'DiagnosticSignInformation'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsInfo', { link = 'DiagnosticSignInfo'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsHint', { link = 'DiagnosticSignHint'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsUnderlineError', { link = 'DiagnosticSignError'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsUnderlineWarning', { link = 'DiagnosticSignWarning'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsUnderlineInformation', { link = 'DiagnosticSignInformation'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsUnderlineInfo', { link = 'DiagnosticSignInfo'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsUnderlineHint', { link = 'DiagnosticSignHint'})
-- Viml links
vim.api.nvim_set_hl(0, 'vimEnvvar', { link = 'Constant'})
vim.api.nvim_set_hl(0, 'vimHiKeyList', { link = 'Constant'})
vim.api.nvim_set_hl(0, 'vimCommand', { link = 'Keyword'})
vim.api.nvim_set_hl(0, 'vimUsrCmd', { link = 'Keyword'})
vim.api.nvim_set_hl(0, 'vimIsCommand', { link = 'Keyword'})
vim.api.nvim_set_hl(0, 'vimNotFunc', { link = 'Keyword'})
vim.api.nvim_set_hl(0, 'vimUserFunc', { link = 'Function'})
vim.api.nvim_set_hl(0, 'vimCommentTitle', { link = 'Special'})
-- Json links
vim.api.nvim_set_hl(0, 'jsonKeyword', { link = 'Keyword'})
vim.api.nvim_set_hl(0, 'jsonBoolean', { link = 'Boolean'})
-- Treesitter links
vim.api.nvim_set_hl(0, 'TSString', { link = 'String'})
vim.api.nvim_set_hl(0, 'TSOperator', { link = 'Operator'})
vim.api.nvim_set_hl(0, 'TSFunction', { link = 'Function'})
vim.api.nvim_set_hl(0, 'TSFuncBuiltin', { link = 'Function'})
vim.api.nvim_set_hl(0, 'TSFuncMacro', { link = 'Function'})
vim.api.nvim_set_hl(0, 'TSError', { link = 'Error'})
vim.api.nvim_set_hl(0, 'TSPunctDelimiter', { link = 'PunctDelimiter'})
vim.api.nvim_set_hl(0, 'TSPunctBracket', { link = 'PunctBracket'})
vim.api.nvim_set_hl(0, 'TSPunctSpecial', { link = 'PunctSpecial'})
vim.api.nvim_set_hl(0, 'TSConstant', { link = 'Constant'})
vim.api.nvim_set_hl(0, 'TSConstBuiltin', { link = 'Constant'})
vim.api.nvim_set_hl(0, 'TSConstMacro', { link = 'Type'})
vim.api.nvim_set_hl(0, 'TSStringRegex', { link = 'String'})
vim.api.nvim_set_hl(0, 'TSStringEscape', { link = 'Operator'})
vim.api.nvim_set_hl(0, 'TSCharacter', { link = 'String'})
vim.api.nvim_set_hl(0, 'TSNumber', { link = 'Number'})
vim.api.nvim_set_hl(0, 'TSBoolean', { link = 'Boolean'})
vim.api.nvim_set_hl(0, 'TSFloat', { link = 'Float'})
vim.api.nvim_set_hl(0, 'TSAnnotation', { link = 'Comment'})
vim.api.nvim_set_hl(0, 'TSAttribute', { link = 'Attribute'})
vim.api.nvim_set_hl(0, 'TSNamespace', { link = 'Namespace'})
vim.api.nvim_set_hl(0, 'TSParameter', { link = 'Identifier'})
vim.api.nvim_set_hl(0, 'TSParameterReference', { link = 'Identifier'})
vim.api.nvim_set_hl(0, 'TSMethod', { link = 'Function'})
vim.api.nvim_set_hl(0, 'TSField', { link = 'Field'})
vim.api.nvim_set_hl(0, 'TSProperty', { link = 'Property'})
vim.api.nvim_set_hl(0, 'TSConstructor', { link = 'Constructor'})
vim.api.nvim_set_hl(0, 'TSConditional', { link = 'Conditional'})
vim.api.nvim_set_hl(0, 'TSRepeat', { link = 'Repeat'})
vim.api.nvim_set_hl(0, 'TSLabel', { link = 'Label'})
vim.api.nvim_set_hl(0, 'TSKeyword', { link = 'Keyword'})
vim.api.nvim_set_hl(0, 'TSKeywordFunction', { link = 'Keyword'})
vim.api.nvim_set_hl(0, 'TSKeywordOperator', { link = 'Keyword'})
vim.api.nvim_set_hl(0, 'TSException', { link = 'Exception'})
vim.api.nvim_set_hl(0, 'TSType', { link = 'Type'})
vim.api.nvim_set_hl(0, 'TSTypeBuiltin', { link = 'Type'})
vim.api.nvim_set_hl(0, 'TSStructure', { link = 'Type'})
vim.api.nvim_set_hl(0, 'TSInclude', { link = 'Include'})
vim.api.nvim_set_hl(0, 'TSVariable', { link = 'Identifier'})
vim.api.nvim_set_hl(0, 'TSVariableBuiltin', { link = 'Identifier'})
vim.api.nvim_set_hl(0, 'TSText', { link = 'Normal'})
vim.api.nvim_set_hl(0, 'TSStrong', { link = 'Strong'})
vim.api.nvim_set_hl(0, 'TSEmphasis', { link = 'Emphasis'})
vim.api.nvim_set_hl(0, 'TSUnderline', { link = 'Underline'})
vim.api.nvim_set_hl(0, 'TSTitle', { link = 'Title'})
vim.api.nvim_set_hl(0, 'TSLiteral', { link = 'Literal'})
vim.api.nvim_set_hl(0, 'TSURI', { link = 'Identifier'})
vim.api.nvim_set_hl(0, 'TSTag', { link = 'Tag'})
vim.api.nvim_set_hl(0, 'TSTagDelimiter', { link = 'TagDelimiter'})
